### ISSUE TITLE
主角build是否要配合道途才有意义?

### ISSUE THREAD

**Issue by fenghou1st** [ZJUZBW/Wotr-BD-LR#1]
虽然一些build不考虑道途也会很厉害, 但是每种build总是有适合的道途及不适合的道途.
就算不配合道途加点, 也可以在最后评价一下和各种道途的兼容性之类的, 给初学者一些参考.

**Comment by ZJUZBW** [comment]
对的，有考虑过这个，但是要考虑全道途也太复杂了。我现在的打算就是把强力组合（即最适合该BD的道途加点）放一起，其他的就给个基础推荐，给大家玩其他道途做个参考。

**Comment by fenghou1st** [comment]
确实, 只要给出强力组合和一般性思路就行了.
